services:
  # PostgreSQL
  dataBase:
    image: postgres:15
    container_name: eldokkan_db
    restart: always
    environment:
      POSTGRES_USER: ahmed
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eldokkan
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: "ahmed@gamal.com"
      PGADMIN_DEFAULT_PASSWORD: "ahmed0000"
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev   
    container_name: eldokkan_Backend
    restart: always
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "pnpm prisma generate &&
             pnpm prisma db push &&
             pnpm run dev"
volumes:
  db_data: